[package]
name = "squashfs-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
byteorder = "1"
flate2 = "1.0"
num_enum = "0.5"
serde = { version = "1.0", features = ["derive"] }